version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgresBD
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    expose:
      - "5432"
    ports:
      - 8000:5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5454:5454/tcp
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5454

  al.interpolation:
    build:
      dockerfile: src/AL.Interpolation/Dockerfile
    ports:
      - "6090:80"
      - "6091:443"
    restart: always

  al.interpolation.client:
    build:
      dockerfile: src/AL.Interpolation.Client/Dockerfile
    deploy:
      replicas: 2
    ports:
      - "6000-6100:80"
    depends_on:
      - al.interpolation
    restart: always

  redis:
   image: 'bitnami/redis:latest'
   environment:
      - ALLOW_EMPTY_PASSWORD=yes
   ports:
      - "6379:6379"
  kafka:
    image: docker.io/bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
   
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8082:8080"
    depends_on:
      - "kafka"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181


  zookeeper:
    image: docker.io/bitnami/zookeeper:latest
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
